name: Update Markdown Links

on: [push]

permissions:
  contents: write

jobs:
  update-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install pyyaml

    - name: Run link update script
      id: update_links
      run: |
        python scripts/update_links.py
        script_exit_code=$?

        if [ $script_exit_code -eq 0 ]; then
          echo "Changes were made."
          echo "::set-output name=changes::true"
        else
          echo "No changes were made."
          echo "::set-output name=changes::false"
        fi

    - name: Commit changes
      if: steps.update_links.outputs.changes == 'true'
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m 'Update markdown links'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
